 %% Model
f_pre_kron= @(x) [x(idx_omega)-1/M_T*M_gen'*x(idx_omega); diag(1./M_gen)*(-D_gen.*x(idx_omega)-E_kron'*diag(bij_pre_kron)*sin(E_kron*x(idx_delta))-abs(E_kron)'*diag(gij_pre_kron)*cos(E_kron*x(idx_delta))+P_pre_kron)-1/M_T*(sum(P_pre_kron)-2*ones(size(E_kron'))*diag(gij_pre_kron)*cos(E_kron*x(idx_delta)))];
J_pre_kron=@(x) [zeros(num_gen) eye(num_gen)-ones(num_gen,1)*M_gen'/M_T; diag(1./M_gen)*(-E_kron'*diag(bij_pre_kron)*diag(cos(E_kron*x(idx_delta)))*E_kron+abs(E_kron)'*diag(gij_pre_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron)-2/M_T*ones(size(E_kron'))*diag(gij_pre_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron -diag(D_gen./M_gen)];
f_fault_kron= @(x) [x(idx_omega)-1/M_T*M_gen'*x(idx_omega); diag(1./M_gen)*(-D_gen.*x(idx_omega)-E_kron'*diag(bij_fault_kron)*sin(E_kron*x(idx_delta))-abs(E_kron)'*diag(gij_fault_kron)*cos(E_kron*x(idx_delta))+P_fault_kron)-1/M_T*(sum(P_pre_kron)-2*ones(size(E_kron'))*diag(gij_fault_kron)*cos(E_kron*x(idx_delta)))];
J_fault_kron=@(x) [zeros(num_gen) eye(num_gen)-ones(num_gen,1)*M_gen'/M_T; diag(1./M_gen)*(-E_kron'*diag(bij_fault_kron)*diag(cos(E_kron*x(idx_delta)))*E_kron+abs(E_kron)'*diag(gij_fault_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron)-2/M_T*ones(size(E_kron'))*diag(gij_fault_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron -diag(D_gen./M_gen)];
f_post_kron= @(x) [x(idx_omega)-1/M_T*M_gen'*x(idx_omega); diag(1./M_gen)*(-D_gen.*x(idx_omega)-E_kron'*diag(bij_post_kron)*sin(E_kron*x(idx_delta))-abs(E_kron)'*diag(gij_post_kron)*cos(E_kron*x(idx_delta))+P_post_kron)-1/M_T*(sum(P_post_kron)-2*ones(size(E_kron'))*diag(gij_post_kron)*cos(E_kron*x(idx_delta)))];
J_post_kron=@(x) [zeros(num_gen) eye(num_gen)-ones(num_gen,1)*M_gen'/M_T; diag(1./M_gen)*(-E_kron'*diag(bij_post_kron)*diag(cos(E_kron*x(idx_delta)))*E_kron+abs(E_kron)'*diag(gij_post_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron)-2/M_T*ones(size(E_kron'))*diag(gij_post_kron)*diag(sin(E_kron*x(idx_delta)))*E_kron -diag(D_gen./M_gen)];

f_post_theta= @(x) -E_kron'*diag(bij_post_kron)*sin(E_kron*x)-abs(E_kron)'*diag(gij_post_kron)*cos(E_kron*x)+P_post_kron-(M_gen/M_T).*(sum(P_post_kron)-2*ones(size(E_kron'))*diag(gij_post_kron)*cos(E_kron*x));
J_post_theta=@(x) -E_kron'*diag(bij_post_kron)*diag(cos(E_kron*x))*E_kron+abs(E_kron)'*diag(gij_post_kron)*diag(sin(E_kron*x))*E_kron-2*diag(M_gen)/M_T*ones(size(E_kron'))*diag(gij_post_kron)*diag(sin(E_kron*x))*E_kron;
